version: '2'
services:
  
  ox_server:
    build:
      context: .
      args:
        - GITHUB_USER
        - GITHUB_TOKEN
    ports:
      - '6617:6617'
    image: ox_herd_image
    container_name: ox_server

